version: '3.5'  

services: 
    service.nginx:
      image: nginx:1.19
      container_name: emby2goindex
      ports: 
        - 8095:80
      volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf 
        - ./conf.d:/etc/nginx/conf.d
      restart: always
